runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  secure: always

- url: .*
  script: router.app
  secure: always

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /site\.webmanifest
  static_files: site.webmanifest
  upload: site\.webmanifest

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
